# Generated by Django 4.0.6 on 2022-07-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=60)),
                ('send_id', models.CharField(max_length=60)),
                ('balance', models.BigIntegerField()),
                ('credit_limit', models.BigIntegerField()),
                ('type', models.CharField(max_length=20)),
                ('currency_code', models.IntegerField()),
                ('cashback_type', models.CharField(max_length=20)),
                ('masked_pan', models.JSONField()),
                ('iban', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BankClient',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('webhook_url', models.CharField(max_length=200)),
                ('permissions', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankJar',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=60)),
                ('send_id', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=300)),
                ('currency_code', models.IntegerField()),
                ('balance', models.BigIntegerField()),
                ('goal', models.BigIntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bankclient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('bank_accounts', models.ManyToManyField(to='transactions.bankaccount')),
                ('bank_clients', models.ManyToManyField(to='transactions.bankclient')),
                ('bank_jars', models.ManyToManyField(to='transactions.bankjar')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('time', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('mcc', models.IntegerField()),
                ('original_mcc', models.IntegerField()),
                ('hold', models.BooleanField()),
                ('amount', models.BigIntegerField()),
                ('operational_amount', models.BigIntegerField()),
                ('currency_code', models.IntegerField()),
                ('commission_rate', models.BigIntegerField()),
                ('cashback_amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('receipt_id', models.CharField(blank=True, max_length=60, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=60, null=True)),
                ('counter_edrpou', models.CharField(blank=True, max_length=60, null=True)),
                ('counter_iban', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.bankaccount')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bankclient')),
                ('jar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.bankjar')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bankclient'),
        ),
    ]
